---
user_name: "ansible-admin"
deploy_root: "/home/ansible-admin"
nas_source_path: "/mnt/NAS/PC1_ai"

# group_vars/AI_Server.yml
git_user_email: "teammate@music.project"
git_server_ip: "10.4.3.10"
project_dir: "/home/ansible-admin/project"
